### PR TITLE
Apparently the illegal push didn't contain the correct staged changes

### PR DESCRIPTION
**Pull request by acheung-94**
so it was both illegal _and_ useless!

### CODE REVIEW

**Comment by ChristopherJTrent** [comment]
apologies for the delay on my review
taking a look

**Comment by ChristopherJTrent** [comment]
This is superceded by #36 
I'd like to close it if there are no objections.

**Comment by acheung-94** [comment]
yes please

**Comment by ChristopherJTrent** [comment]
Closing as duplicate

**Pull request closed without merging**
